# Generated by Django 3.1.6 on 2021-02-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
